package aimasker.burp;

import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.function.UnaryOperator;

/**
 * Renders findings as a self-contained, print-ready HTML report. The styling is a restrained
 * dark theme (slate background, steel-blue accents, muted severity colours) meant to read like a
 * hand-crafted security report - deliberately none of the neon purple/aqua "AI" look. It prints
 * to PDF faithfully because backgrounds are forced on for print.
 */
public final class ReportRenderer {

    private static final DateTimeFormatter STAMP = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    private ReportRenderer() {
    }

    /**
     * @param unmask restores real values in the AI's masked summaries for this local report
     */
    public static String html(List<Finding> findings, UnaryOperator<String> unmask) {
        long high = findings.stream().filter(Finding::vulnerable).count();
        long pot = findings.stream().filter(Finding::potential).count();
        StringBuilder b = new StringBuilder();
        b.append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">")
                .append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
                .append("<title>Security Findings</title>").append("<style>").append(css()).append("</style></head><body>");

        b.append("<header class=\"cover\">")
                .append("<div class=\"mark\">CLOAK</div>")
                .append("<h1>Security Findings</h1>")
                .append("<p class=\"sub\">AI-assisted analysis &mdash; findings require manual confirmation before action.</p>")
                .append("<div class=\"meta\"><span>Generated ").append(LocalDateTime.now().format(STAMP))
                .append("</span><span>").append(findings.size()).append(" finding(s)</span></div>")
                .append("</header>");

        b.append("<section class=\"summary\">")
                .append(stat(String.valueOf(findings.size()), "Total", "accent"))
                .append(stat(String.valueOf(high), "Confirmed", "high"))
                .append(stat(String.valueOf(pot), "Potential", "warn"))
                .append("</section>");

        if (findings.isEmpty()) {
            b.append("<p class=\"empty\">No findings recorded.</p>");
        }
        int i = 1;
        for (Finding f : findings) {
            String sev = f.vulnerable() ? "high" : f.potential() ? "potential" : "info";
            String sevLabel = f.vulnerable() ? "HIGH" : f.potential() ? "POTENTIAL" : f.status();
            String title = f.title() == null || f.title().isBlank() ? f.endpoint() : f.title();
            b.append("<article class=\"finding sev-").append(sev).append("\">")
                    .append("<div class=\"fhead\"><span class=\"idx\">").append(i++).append("</span>")
                    .append("<span class=\"ftitle\">").append(esc(title)).append("</span>")
                    .append("<span class=\"chip chip-").append(sev).append("\">").append(esc(sevLabel)).append("</span></div>")
                    .append("<code class=\"endpoint\">").append(esc(f.endpoint())).append("</code>")
                    .append("<div class=\"grid\">")
                    .append(row("Target", esc((f.secure() ? "https" : "http") + "://" + f.host() + ":" + f.port())))
                    .append(row("Status", esc(f.status())))
                    .append(row("Observed", esc(f.time())))
                    .append("</div>")
                    .append("<div class=\"detail\">").append(prose(unmask.apply(f.summary()))).append("</div>");
            String request = preview(f.request(), 2600);
            if (!request.isBlank()) {
                b.append("<div class=\"evidence\"><div class=\"elabel\">Request (local, unmasked)</div><pre>")
                        .append(esc(request)).append("</pre></div>");
            }
            b.append("</article>");
        }

        b.append("<footer class=\"foot\">Generated by Cloak &middot; AI-assisted security analysis gateway. "
                + "Pseudonyms were used while sharing data with the model; this local report shows real values.</footer>");
        b.append("</body></html>");
        return b.toString();
    }

    private static String stat(String value, String label, String tone) {
        return "<div class=\"stat tone-" + tone + "\"><div class=\"num\">" + esc(value)
                + "</div><div class=\"lbl\">" + esc(label) + "</div></div>";
    }

    private static String row(String k, String v) {
        return "<div class=\"cell\"><span class=\"k\">" + esc(k) + "</span><span class=\"v\">" + v + "</span></div>";
    }

    /** Turns plain/markdown-ish summary text into simple paragraphs, escaping HTML. */
    private static String prose(String text) {
        StringBuilder out = new StringBuilder();
        for (String para : text.strip().split("\\n\\s*\\n")) {
            if (!para.isBlank()) {
                out.append("<p>").append(esc(para.strip()).replace("\n", "<br>")).append("</p>");
            }
        }
        return out.length() == 0 ? "<p class=\"muted\">(no summary)</p>" : out.toString();
    }

    private static String preview(byte[] bytes, int max) {
        if (bytes == null || bytes.length == 0) {
            return "";
        }
        String s = new String(bytes, StandardCharsets.ISO_8859_1);
        return s.length() > max ? s.substring(0, max) + "\n… [truncated]" : s;
    }

    private static String esc(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private static String css() {
        return ""
            + "*{box-sizing:border-box}"
            + ":root{--bg:#1b1f27;--surface:#232835;--surface2:#1e232e;--border:#333b4a;--text:#d8dee9;"
            + "--muted:#8a93a6;--accent:#81a1c1;--high:#bf616a;--info:#a3be8c;--warn:#ebcb8b;--mono:#e5e9f0}"
            + "html,body{margin:0;background:var(--bg);color:var(--text);"
            + "font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;"
            + "font-size:13.5px;line-height:1.6;-webkit-print-color-adjust:exact;print-color-adjust:exact}"
            + ".cover{padding:40px 44px 28px;border-bottom:1px solid var(--border)}"
            + ".mark{font:600 12px/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.28em;"
            + "color:var(--accent);opacity:.9}"
            + "h1{margin:14px 0 6px;font-size:30px;font-weight:650;letter-spacing:-.01em;color:#eceff4}"
            + ".sub{margin:0;color:var(--muted);font-size:13px}"
            + ".meta{margin-top:16px;display:flex;gap:20px;color:var(--muted);font-size:12px}"
            + ".meta span{border:1px solid var(--border);border-radius:3px;padding:4px 10px}"
            + ".summary{display:flex;gap:14px;padding:24px 44px}"
            + ".stat{flex:1;background:var(--surface);border:1px solid var(--border);border-radius:3px;padding:16px 18px}"
            + ".stat .num{font-size:26px;font-weight:650}.stat .lbl{color:var(--muted);font-size:11.5px;"
            + "text-transform:uppercase;letter-spacing:.06em;margin-top:2px}"
            + ".tone-accent .num{color:var(--accent)}.tone-high .num{color:var(--high)}"
            + ".tone-warn .num{color:var(--warn)}.tone-muted .num{color:var(--muted)}"
            + ".finding{margin:16px 44px;background:var(--surface);border:1px solid var(--border);"
            + "border-left:3px solid var(--border);border-radius:3px;padding:18px 20px;break-inside:avoid}"
            + ".finding.sev-high{border-left-color:var(--high)}.finding.sev-info{border-left-color:var(--info)}"
            + ".finding.sev-potential{border-left-color:var(--warn)}"
            + ".fhead{display:flex;align-items:center;gap:12px}"
            + ".idx{font:600 12px/1.6 ui-monospace,Menlo,Consolas,monospace;color:var(--muted);min-width:20px}"
            + ".ftitle{flex:1;font-size:16px;font-weight:600;color:#eceff4}"
            + ".endpoint{display:inline-block;margin:8px 0 2px;font:500 12.5px/1.5 ui-monospace,SFMono-Regular,"
            + "Menlo,Consolas,monospace;color:var(--mono);background:var(--surface2);border:1px solid var(--border);"
            + "border-radius:3px;padding:3px 9px;overflow-wrap:anywhere}"
            + ".chip{font-size:10.5px;font-weight:700;letter-spacing:.05em;padding:3px 9px;border-radius:3px;"
            + "border:1px solid}"
            + ".chip-high{color:var(--high);border-color:var(--high);background:rgba(191,97,106,.12)}"
            + ".chip-info{color:var(--info);border-color:var(--info);background:rgba(163,190,140,.12)}"
            + ".chip-potential{color:var(--warn);border-color:var(--warn);background:rgba(235,203,139,.12)}"
            + ".grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0 4px}"
            + ".cell{background:var(--surface2);border:1px solid var(--border);border-radius:3px;padding:8px 10px}"
            + ".cell .k{display:block;color:var(--muted);font-size:10.5px;text-transform:uppercase;letter-spacing:.06em}"
            + ".cell .v{font:500 12px/1.5 ui-monospace,Menlo,Consolas,monospace;overflow-wrap:anywhere}"
            + ".detail{margin-top:8px}.detail p{margin:8px 0}.muted{color:var(--muted)}"
            + ".evidence{margin-top:12px}.elabel{color:var(--muted);font-size:11px;text-transform:uppercase;"
            + "letter-spacing:.06em;margin-bottom:6px}"
            + "pre{margin:0;background:var(--surface2);border:1px solid var(--border);border-radius:3px;padding:12px 14px;"
            + "font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:var(--mono);"
            + "white-space:pre-wrap;overflow-wrap:anywhere}"
            + ".foot{margin:28px 44px 40px;padding-top:16px;border-top:1px solid var(--border);color:var(--muted);"
            + "font-size:11px}"
            + ".empty{margin:40px 44px;color:var(--muted)}"
            + "@page{size:A4;margin:0}";  // no page margin -> dark fills edge to edge, no white strips
    }
}
